### ISSUE TITLE
grep -P does not exist on Mac OS X

### ISSUE THREAD

**Issue by mitar** [tozd/meteor-test-runner#1]
https://stackoverflow.com/questions/16658333/grep-p-no-longer-works-how-can-i-rewrite-my-searches

**Comment by tinhphaius** [comment]
Fix

**Comment by mitar** [comment]
?

**Comment by mitar** [comment]
We use GNU grep now on Mac OS X. One has to install it themselves. I did:

```
brew install grep
```

**Comment by mitar** [comment]
This is also documented in README.
